### PR TITLE
Safety branch v2.0

### PR DESCRIPTION
**Pull request by sidselKorch**

### CODE REVIEW

**Comment by Yuni-S** [comment]
Yes!

**Comment by Yuni-S** [comment]
...

**Comment by Yuni-S** [comment]
<3

**Review by Evgenios95 — COMMENTED** [review]
I tested the application and everything works fine. This time the feedback is not thorough, as I can see that you chose not to implement any of the suggestions or react/ comment/ resolve any of my comments :D

Just a small comment, something is off with updating your users, some fields go blank after saving the changes, you could look into it!

Also, TAs review your assignments, and not Bjørn. So make sure you add me, Helena and Louie as contributors and as reviewers every time you make a PR.

**Comment by Yuni-S** [comment]
...

**Comment by Yuni-S** [comment]
Yes!

**Comment by Yuni-S** [comment]
<3

**Review by Yuni-S — APPROVED** [review]

**Comment by sidselKorch** [comment]
> I tested the application and everything works fine. This time the feedback is not thorough, as I can see that you chose not to implement any of the suggestions or react/ comment/ resolve any of my comments :D
> 
> Just a small comment, something is off with updating your users, some fields go blank after saving the changes, you could look into it!
> 
> Also, TAs review your assignments, and not Bjørn. So make sure you add me, Helena and Louie as contributors and as reviewers every time you make a PR.


Sidsel:
We didn't manage to look into this issue with the updating users at this point, however we have handled, commented and resolved the comments in the previous pull request on safety_branch_v1.0. :)

To the last comment, we have invited you all from the first sprint, and the status have been pending invites ever since, that is why we have only been able to request review from Bjørn. At sprint 2 i invited again as the pending invites had expired and now their status is pending invites. I dont know, but dont think that im doing it wrong, as bjørn has gotten the invite.

**Pull request merged**
